<?php

/**
 * @file
 * Install, update and uninstall functions for the initializer module.
 */

/**
 * Implements hook_install().
 */
function initializer_install() {
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'bootstrap')
    ->execute();
  variable_set('theme_default', 'bootstrap');
}

/**
 * Implements hook_uninstall().
 */
function initializer_uninstall() {
 
}
