<?php

/**
 *  Implementation of hook_install
*/
function gallery_demo_hack_install() {

   _create_photo_node('gallery-display-main', 'photo', 'photo 1', array('file_name' => 'photo_1.jpg','alternate_text' =>'photo 1 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 2', array('file_name' => 'photo_2.jpg','alternate_text' =>'photo 2 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 3', array('file_name' => 'photo_3.jpg','alternate_text' =>'photo 3 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 4', array('file_name' => 'photo_4.jpg','alternate_text' =>'photo 4 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 5', array('file_name' => 'photo_5.jpg','alternate_text' =>'photo 5 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 6', array('file_name' => 'photo_6.jpg','alternate_text' =>'photo 6 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 7', array('file_name' => 'photo_7.jpg','alternate_text' =>'photo 7 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 8', array('file_name' => 'photo_8.jpg','alternate_text' =>'photo 8 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 9', array('file_name' => 'photo_9.jpg','alternate_text' =>'photo 9 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 10', array('file_name' => 'photo_10.jpg','alternate_text' =>'photo 10 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 11', array('file_name' => 'photo_11.jpg','alternate_text' =>'photo 11 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 12', array('file_name' => 'photo_12.jpg','alternate_text' =>'photo 12 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 13', array('file_name' => 'photo_13.jpg','alternate_text' =>'photo 13 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 14', array('file_name' => 'photo_14.jpg','alternate_text' =>'photo 14 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 15', array('file_name' => 'photo_15.jpg','alternate_text' =>'photo 15 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 16', array('file_name' => 'photo_16.jpg','alternate_text' =>'photo 16 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 17', array('file_name' => 'photo_17.jpg','alternate_text' =>'photo 17 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 18', array('file_name' => 'photo_18.jpg','alternate_text' =>'photo 18 Image Alternate text'));
   
   _create_photo_node('gallery-display-main', 'photo', 'photo 19', array('file_name' => 'photo_19.jpg','alternate_text' =>'photo 19 Image Alternate text'));
  
   _create_photo_node('gallery-display-main', 'photo', 'photo 20', array('file_name' => 'photo_20.jpg','alternate_text' =>'photo 20 Image Alternate text'));
}


function _create_photo_node($display_area, $node_type, $title, $image) {
  $node = new stdClass();
  $node->type = $node_type;
  $node->language = LANGUAGE_NONE;
  node_object_prepare($node);
  $node->sticky = 0;
  $node->title = t($title);
  $node->status = 1;
  $node->revision = 0;
  $node->promote = 0;
  
  $filepath = drupal_get_path('module', 'photo_demo_hack') . '/images/' . $image['file_name'];
  $file = (object) array(
      'uid' => 1,
      'uri' => $filepath,
      'filemime' => file_get_mimetype($filepath),
      'status' => 1,
  );
  $file = file_copy($file, 'public://');    // We save the file to the root of the files directory.
  $node->field_image[$node->language][0] = (array) $file;  //attach image to field!
  
  $node->field_image[$node->language][0]['alt'] = $image['alternate_text'];
  $node->field_display_area[$node->language][0]['value'] = $display_area;    
  $node = node_submit($node);
  node_save($node);  
}


/**
 *  Implementation of hook_uninstall
*/
function gallery_demo_hack_uninstall() {
  
}