<?php

/**
 * Implements hook_install().
 */
function core_initializer_install() {
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'bootstrap')
    ->execute();
  variable_set('theme_default', 'bootstrap');
  variable_set('admin_theme', 'seven');
}

/**
 * Implements hook_uninstall().
 */
function core_initializer_uninstall() {
 
}
