<?php

/**
 *  Implementation of hook_install
*/
function rig_demo_hack_install() {
    
   $image_instance_info = field_info_instance('node', 'field_image', 'rig');
   if ($image_instance_info != NULL) {
    $images_path = drupal_realpath('public://') . '/' . $image_instance_info['settings']['file_directory'];
    file_prepare_directory($images_path, FILE_CREATE_DIRECTORY);
   }
   $rig_desc_1 = 'These late model rigs are truck mounted and equipped for hollow-stem auger, mud rotary drilling, air and rock coring. All rigs have been converted to high torque configuration for difficult drilling conditions; most have 140 lb. and 300 lb. auto-hammers. Auger sizes range from 4" to 24"  O.D.';
   _create_rig_node('Truckmount', 'rig', '95 High Torque', '1', '350\' + with 8" diameter hole', $rig_desc_1, array('file_name' => '95HighTorque_Truckmount.jpg','alternate_text' =>'95 High Torque'));
  
   _create_rig_node('Truckmount', 'rig', 'Failing F-10 High Torque', '1', '350\' + with 8" diameter hole', '', array('file_name' => 'FailingF10_Truckmount.jpg','alternate_text' =>'Failing F-10 High Torque'));
  
}


function _create_rig_node($rig_category, $node_type, $title, $quantity, $depths_diameters_drilled, rig_desc, $image) {
  $node = new stdClass();
  $node->type = $node_type;
  $node->language = LANGUAGE_NONE;
  node_object_prepare($node);
  $node->sticky = 0;
  $node->title = t($title);
  $node->status = 1;
  $node->revision = 0;
  $node->promote = 0;
  
  $image_instance_info = field_info_instance('node', 'field_feature_image', 'rig');
  if ($image_instance_info != NULL) {
    $filepath = drupal_get_path('module', 'rig_demo_hack') . '/images/' . $image['file_name'];
    $file = (object) array(
        'uid' => 1,
        'uri' => $filepath,
        'filemime' => file_get_mimetype($filepath),
        'status' => 1,
    );
    $file = file_copy($file, 'public://'. $image_instance_info['settings']['file_directory']);    // We save the file to the root of the files directory.
    $node->field_feature_image[$node->language][0] = (array) $file;  //attach image to field!
  }
  
  $node->field_feature_image[$node->language][0]['alt'] = $image['alternate_text'];
  $node->field_rig_category[$node->language][0]['value'] = $rig_category;
  $node->field_quantity[$node->language][0]['value'] = $quantity;
  $node->field_depths_diameters_drilled[$node->language][0]['value'] = $depths_diameters_drilled;
  $node->body[$node->language][0]['value'] = $rig_desc;
  
  $node = node_submit($node);
  node_save($node);  
}


/**
 *  Implementation of hook_uninstall
*/
function rig_demo_hack_uninstall() {
  
}